name: Salesforce CI

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Check Salesforce CLI version
        run: sf --version

      - name: Say hello
        run: echo "Salesforce CLI installed successfully"
